Repository KILTprotocol/portablegabi, pull requests merged in 2020-04, with the labels that each got.

#30 Update dependencies
  jest.config.js
  package.json
  yarn.lock
Labels: dependencies

#31 feat: wait until transaction is finalized
  docs/examples/exampleCombined.chain.ts
  docs/examples/exampleSingle.chain.ts
  docs/examples/exampleSingle.mashnet.ts
  docs/examples/onchain/1_actorProcess.ts
  src/attestation/Attester.chain.spec.ts
  src/blockchain/Blockchain.integration.spec.ts
  src/blockchain/Blockchain.spec.ts
  src/blockchain/Blockchain.ts
  src/blockchain/__mocks__/BlockchainApi.ts
  src/types/Chain.ts
Labels: enhancement

#32 feat: add optional key length parameter
  docs/examples/offchain/1_actorProcess.ts
  docs/examples/offchain/2_issuanceProcess.ts
  docs/examples/offchain/3_verificationProcessCombined.ts
  docs/examples/onchain/1_actorProcess.ts
  docs/examples/onchain/3_verificationProcessCombined.ts
  go-wasm/pkg/wasm/attester.go
  go-wasm/pkg/wasm/claimer.go
  go-wasm/pkg/wasm/helper.go
  go-wasm/pkg/wasm/verifier.go
  src/attestation/Attester.chain.ts
  src/attestation/Attester.spec.ts
  src/attestation/Attester.ts
  src/claim/Claimer.spec.ts
  src/claim/Claimer.ts
  src/types/Attestation.ts
  src/types/Chain.ts
  src/types/Verification.ts
  src/verification/Verifier.ts
Labels: enhancement

#14 Fixes for sdk
  go-wasm/Gopkg.lock
  go-wasm/Gopkg.toml
  go-wasm/main.go
  go-wasm/main_test.go
  go-wasm/pkg/credentials/claim.go
  go-wasm/pkg/credentials/claim_test.go
  go-wasm/pkg/credentials/claimer.go
  go-wasm/pkg/credentials/claimer_test.go
  go-wasm/pkg/credentials/contants_test.go
  go-wasm/pkg/wasm/attester.go
  go-wasm/pkg/wasm/claimer.go
  package.json
  src/attestation/Attester.ts
  src/claim/Claimer.spec.ts
  src/claim/Claimer.ts
  src/types/Verification.ts
  src/verification/CombinedRequestBuilder.spec.ts
  src/verification/Verifier.spec.ts
  src/verification/Verifier.ts
  src/wasm/WasmHooks.ts
Labels: enhancement

#34 Improve WASM closing
  docs/examples/exampleCombined.chain.ts
  docs/examples/exampleCombined.ts
  docs/examples/exampleSingle.chain.ts
  docs/examples/exampleSingle.ts
  docs/examples/onchain/1_actorProcess.ts
  go-wasm/main.go
  src/testSetup/jest.teardown.js
  src/wasm/WasmHooks.ts
  src/wasm/wasm_exec_wrapper.spec.ts
  src/wasm/wasm_exec_wrapper.ts
Labels: enhancement

#36 Add examples to CI
  .github/workflows/test.yml
  docs/examples/exampleCombined.chain.ts
  docs/examples/exampleCombined.ts
  docs/examples/exampleSingle.chain.ts
  docs/examples/exampleSingle.ts
  docs/examples/offchain/4_teardown.ts
Labels: enhancement

#37 Remove parseCache from credential
  src/claim/Credential.ts
Labels: refactor

#38 Replace String with WasmData inheritance
  .github/workflows/test.yml
  README.md
  docs/examples/offchain/1_actorProcess.ts
  docs/examples/onchain/1_actorProcess.ts
  docs/examples/readme.ts
  jest.config.js
  src/attestation/Accumulator.spec.ts
  src/attestation/Accumulator.ts
  src/attestation/Attester.chain.spec.ts
  src/attestation/Attester.spec.ts
  src/attestation/Attester.ts
  src/blockchain/Blockchain.integration.spec.ts
  src/blockchain/Blockchain.spec.ts
  src/blockchain/Blockchain.ts
  src/blockchain/__mocks__/BlockchainApi.ts
  src/claim/Claimer.spec.ts
  src/claim/Claimer.ts
  src/claim/Credential.chain.spec.ts
  src/claim/Credential.ts
  src/testSetup/testTypes.ts
  src/types/Attestation.ts
  src/types/Claim.ts
  src/types/Verification.ts
  src/types/Wasm.ts
  src/verification/Verifier.spec.ts
  src/verification/Verifier.ts
  src/wasm/wasm_exec_wrapper.ts
Labels: refactor
